[build]
  publish = "frontend"

[[redirects]]
  from = "/"
  to = "/app/"
  status = 302

[[redirects]]
  from = "/app"
  to = "/app/"
  status = 301

[[redirects]]
  from = "/app/*"
  to = "/pwa/:splat"
  status = 200

